apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-exporter
  template:
    metadata:
      labels:
        app: nginx-exporter
    spec:
      containers:
      - name: nginx-exporter
        image: nginx/nginx-prometheus-exporter
        args:
        - "-nginx.scrape-uri=http://{{ .Values.nginxExporter.scrapeHost }}:{{ .Values.nginxExporter.scrapePort }}/metrics"
        ports:
        - containerPort: 9113
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-exporter
  labels:
    app: web-monitor
spec:
  selector:
    app: nginx-exporter
  ports:
  - protocol: TCP
    port: 9113
    targetPort: 9113
    nodePort: 30113
    name: web-port
  type: NodePort