apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    prometheus: main
    app: web-monitor
spec:
  selector:
    matchLabels:
      app: web-monitor
  endpoints:
    - port: web-port
      path: /metrics
      interval: 30s