apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-test
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/helloitsurdvq/web_test
      path: charts
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/values.yaml
          
  destination:
    server: https://kubernetes.default.svc
    namespace: web